#ifndef _KEYMAP_H_
#define _KEYMAP_H_

typedef enum {
	KB_RESERVED = 0,
	KB_ESC,
	KB_1,
	KB_2,
	KB_3,
	KB_4,
	KB_5,
	KB_6,
	KB_7,
	KB_8,
	KB_9,
	KB_0,
	KB_MINUS,
	KB_EQUALS,
	KB_BACKSPACE,
	KB_TAB,
	KB_Q,
	KB_W,
	KB_E,
	KB_R,
	KB_T,
	KB_Y,
	KB_U,
	KB_I,
	KB_O,
	KB_P,
	KB_LEFTBRACE,
	KB_RIGHTBRACE,
	KB_ENTER,
	KB_LEFTCTRL,
	KB_A,
	KB_S,
	KB_D,
	KB_F,
	KB_G,
	KB_H,
	KB_J,
	KB_K,
	KB_L,
	KB_SEMICOLON,
	KB_APOSTROPHE,
	KB_GRAVE,
	KB_LEFTSHIFT,
	KB_BACKSLASH,
	KB_Z,
	KB_X,
	KB_C,
	KB_V,
	KB_B,
	KB_N,
	KB_M,
	KB_COMMA,
	KB_DOT,
	KB_SLASH,
	KB_RIGHTSHIFT,
	KB_KPASTERISK,
	KB_LEFTALT,
	KB_SPACE,
	KB_CAPSLOCK,
	KB_UP,
	KB_LEFT,
	KB_RIGHT,
	KB_DOWN,
	KB_MAX
} Keymap;

#ifdef __linux__
static const Keymap linux_to_keymap[] =  
{
	KB_RESERVED,	//KEY_RESERVED
	KB_ESC,	//KEY_ESCAPE
	KB_1,	//KEY_1
	KB_2,	//KEY_2
	KB_3,	//KEY_3
	KB_4,	//KEY_4
	KB_5,	//KEY_5
	KB_6,	//KEY_6
	KB_7,	//KEY_7
	KB_8,	//KEY_8
	KB_9,	//KEY_9
	KB_0,	//KEY_0
	KB_MINUS,	//KEY_MINUS
	KB_EQUALS,	//KEY_EQUALS
	KB_BACKSPACE,	//KEY_BACKSPACE
	KB_TAB,	//KEY_TAB
	KB_Q,	//KEY_Q
	KB_W,	//KEY_W
	KB_E,	//KEY_E
	KB_R,	//KEY_R
	KB_T,	//KEY_T
	KB_Y,	//KEY_Y
	KB_U,	//KEY_U
	KB_I,	//KEY_I
	KB_O,	//KEY_O
	KB_P,	//KEY_P
	KB_LEFTBRACE,	//KEY_LEFTBRACE   
	KB_RIGHTBRACE,	//KEY_RIGHTBRACE   
	KB_ENTER,	//KEY_ENTER
	KB_LEFTCTRL,	//KEY_LEFTCTRL is 17 correct?
	KB_A,	//KEY_A
	KB_S,	//KEY_S
	KB_D,	//KEY_D
	KB_F,	//KEY_F
	KB_G,	//KEY_G
	KB_H,	//KEY_H
	KB_J,	//KEY_J
	KB_K,	//KEY_K
	KB_L,	//KEY_L
	KB_SEMICOLON,	//KEY_SEMICOLON
	KB_APOSTROPHE,	//KEY_APOSROPHE
	KB_GRAVE,	//KEY_GRAVE not sure about this one at all
	KB_LEFTSHIFT,	//KEY_LEFTSHIFT
	KB_BACKSLASH,	//KEY_BACKSLASH ???
	KB_Z,	//KEY_Z
	KB_X,	//KEY_X
	KB_C,	//KEY_C
	KB_V,	//KEY_V
	KB_B,	//KEY_B
	KB_N,	//KEY_N
	KB_M,	//KEY_M
	KB_COMMA,	//KEY_COMMA
	KB_DOT,	//KEY_DOT
	KB_SLASH,	//KEY_SLASH 53
	KB_RIGHTSHIFT,	//KEY_RIGHTSHIFT
	KB_KPASTERISK,	//KEY_KPASTERISK
	KB_LEFTALT,	//KEY_LEFTALT
	KB_SPACE,	//KEY_SPACE
	KB_CAPSLOCK,	//KEY_CAPSLOCK
	KB_RESERVED,	//   59,	//KEY_F1
	KB_RESERVED,	//   60,	//KEY_F2
	KB_RESERVED,	//   61,	//KEY_F3
	KB_RESERVED,	//62,	//KEY_F4
	KB_RESERVED,	//63,	//KEY_F5
	KB_RESERVED,	//64,	//KEY_F6
	KB_RESERVED,	//65,	//KEY_F7
	KB_RESERVED,	//66,	//KEY_F8
	KB_RESERVED,	//67,	//KEY_F9
	KB_RESERVED,	//68,	//KEY_F10	   
	KB_RESERVED,	//69,	//KEY_NUMLOCK
	KB_RESERVED,	//70,	//KEY_SCROLLLOCL
	KB_RESERVED,	//71,	//KEY_KP7
	KB_RESERVED,	//72,	//KEY_KP8
	KB_RESERVED,	//73,	//KEY_KP9
	KB_RESERVED,	//74,	//KEY_KPMINUS
	KB_RESERVED,	//75,	//KEY_KP4
	KB_RESERVED,	//76,	//KEY_KP5
	KB_RESERVED,	//77,	//KEY_KP6
	KB_RESERVED,	//78,	//KEY_KPPLUS
	KB_RESERVED,	//79,	//KEY_KP1
	KB_RESERVED,	//80,	//KEY_KP2
	KB_RESERVED,	//81,	//KEY_KP3
	KB_RESERVED,	//82,	//KEY_KP0
	KB_RESERVED,	//83,	//KEY_KPDOT
	KB_RESERVED,	//84,	
	KB_RESERVED,	//85,	
	KB_RESERVED,	//86,	
	KB_RESERVED,	//87,	
	KB_RESERVED,	//88,	
	KB_RESERVED,	//89,	
	KB_RESERVED,	//90,
	KB_RESERVED,	//91,
	KB_RESERVED,	//92,
	KB_RESERVED,	//93,
	KB_RESERVED,	//94,	
	KB_RESERVED,	//95,	//KEY_KP_COMMA
	KB_RESERVED,	//96,	
	KB_RESERVED,	//97,	//KEY_RIGHTCTRL
	KB_RESERVED,	//98,	
	KB_RESERVED,	//99,	
	KB_RESERVED,	//100,	//KEY_RIGHTALT
	KB_RESERVED,	//101,	
	KB_RESERVED,	//102,	//KEY_HOME
	KB_UP,			//103,	//KEY_UP
	KB_RESERVED,	//104,	//KEY_PAGEUP
	KB_LEFT,		//105,	//KEY_LEFT
	KB_RIGHT,		//106,	//KEY_RIGHT
	KB_RESERVED,	//107,	//KEY_END
	KB_DOWN,		//108,	//KEY_DOWN
	KB_RESERVED,	//109,	
	KB_RESERVED,	//100,
	KB_RESERVED,	//111,
	KB_RESERVED,	//112,
	KB_RESERVED,	//113,
	KB_RESERVED,	//114,	
	KB_RESERVED,	//115,	
	KB_RESERVED,	//116,	
	KB_RESERVED,	//117,	
	KB_RESERVED,	//118,	
	KB_RESERVED,	//119,	
	KB_RESERVED,	//120 //we'll stop here for now as we've got most of the keys of interest
};
#define LINUX_KB_MAX 120
#endif

#endif //_KEYMAP_H_